# POST http://localhost:8080/auth/owner/signin
# Content-Type: application/json

# {
#   "username": "owner",
#   "password": "ownerpassword"
# }

POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "tenant",
  "password": "ownerpassword"
}