# POST http://localhost:8080/auth/owner/signup
# Content-Type: application/json

# {
#   "username": "owner",
#   "password": "ownerpassword",
#   "role": "OWNER"
# }

# POST http://localhost:8080/auth/owner/signin
# Content-Type: application/json

# {
#   "username": "owner",
#   "password": "ownerpassword"
# }

# POST http://localhost:8080/auth/signin
# Content-Type: application/json

# {
#   "username": "tenant",
#   "password": "ownerpassword"
# }

# DELETE http://localhost:8080/api/property/delete/property/3
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciAyIiwiaWF0IjoxNzEwNzg4MzUyLCJleHAiOjE3MTA4NzQ3NTJ9.cdTbZlLD-8mS1pZSfHgqkaYaXOoxJiKUCmW_a_SN-Lo


# POST http://localhost:8080/api/property/create
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImlhdCI6MTcxMDgzMjcwNSwiZXhwIjoxNzEwOTE5MTA1fQ.n2fcV_K_j9u8FDs2EALjTyMflZ6fe58aGeMHUFZ0VzI

# {
#   "name": "House for owner",
#   "description": "A spacious and modern apartment",
#   "size": 200.5,
#   "location": "City Center updated",
#   "price": 500000.0,
#   "propertyImageUrl": "https://example.com/image.jpg",
#   "propertyType": "RESIDENTIAL"
# }

POST http://localhost:8080/api/apartment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImlhdCI6MTcxMDgzMjcwNSwiZXhwIjoxNzEwOTE5MTA1fQ.n2fcV_K_j9u8FDs2EALjTyMflZ6fe58aGeMHUFZ0VzI


{
  "apartmentType": "ONE_BEDROOM",
  "size": 50.0,
  "price": 17500.0,
  "apartmentImageUrl": "https://example.com/image.jpg",
  "propertyId": 1,
  "isAvailable" : false
}

# DELETE http://localhost:8080/api/apartment/delete/1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImlhdCI6MTcxMDgzMjcwNSwiZXhwIjoxNzEwOTE5MTA1fQ.n2fcV_K_j9u8FDs2EALjTyMflZ6fe58aGeMHUFZ0VzI


# GET http://localhost:8080/api/property/list/all-properties
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciAyIiwiaWF0IjoxNzEwNzg4MzUyLCJleHAiOjE3MTA4NzQ3NTJ9.cdTbZlLD-8mS1pZSfHgqkaYaXOoxJiKUCmW_a_SN-Lo

# GET http://localhost:8080/api/property/list/my-properties
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImlhdCI6MTcxMDgzMjcwNSwiZXhwIjoxNzEwOTE5MTA1fQ.n2fcV_K_j9u8FDs2EALjTyMflZ6fe58aGeMHUFZ0VzI


# GET http://localhost:8080/api/apartment/all/list
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJvd25lciIsImlhdCI6MTcxMDgzMjcwNSwiZXhwIjoxNzEwOTE5MTA1fQ.n2fcV_K_j9u8FDs2EALjTyMflZ6fe58aGeMHUFZ0VzI
